name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Container Image
        working-directory: ./Dockerizing/10-naming-server
        run: mvn spring-boot:build-image -DskipTests

      - name: Build API Gateway Container Image
        working-directory: ./Dockerizing/10-api-gateway
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Cambio Microservice Jar
        working-directory: ./Dockerizing/10-cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Microservice Jar
        working-directory: ./Dockerizing/10-book-service
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: ./Dockerizing
        run: docker-compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/naming-server:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest ${{ secrets.DOCKER_USERNAME }}/cambio-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:latest ${{ secrets.DOCKER_USERNAME }}/book-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cambio-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:latest
